feat/ disableDotRule in dev mode
openedx/frontend-build pull request #249
Opened 2022-06-11 07:03 UTC by DAN3002

Sometime we have course with dot in the course code (i.e WEB101x_2,.1) so we should disable dot rule in webpack to allow . in route for MFE.

2022-06-11 07:03 UTC, openedx-webhooks commented
Thanks for the pull request, @DAN3002! I've created [OSPR-6784](https://openedx.atlassian.net/browse/OSPR-6784) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-07-20 17:26 UTC, natabene commented
@DAN3002 Thank you for submitting the form, apologies for the delay. The CLA check is green now and we will be able to review your code soon.

2022-07-26 14:22 UTC, adamstankiewicz requested changes
@DAN3002 This change makes sense to me! I think we should also make a similar change in the other default dev server Webpack, i.e., `webpack-dev-stage.config.js`, though so it's consistent between development configurations.

2023-01-11 10:10 UTC, itsjeyd commented
Hey @DAN3002, just checking in to see if these changes are still relevant?

2023-01-30 13:56 UTC, arbrandes commented
@DAN3002, ping! :)

2023-02-08 10:30 UTC, itsjeyd commented
Hi @DAN3002! Thanks again for your contribution! We’re closing this PR at this time because it is stale. You may reopen this pull request, or open a new one, when you have time to come back to this work.

2023-02-08 10:30 UTC, closed without merging

2023-02-08 10:30 UTC, openedx-webhooks commented
@DAN3002 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-build&entry.867055334=https://github.com/openedx/frontend-build/pull/249&entry.1484655318=https://github.com/DAN3002&entry.752974735=2022-06-11+07:03&entry.1917517419=2023-02-08+10:30&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->