Adding codecov action to workflows
openedx/frontend-build pull request #251
Opened 2022-06-15 11:15 UTC by mamankhan99

codecov action added to the ci that uploads coverage report to [codecov.io](https://codecov.io)

2022-06-16 16:42 UTC, arbrandes requested changes
A very, very minor nitpick: otherwise, good to go.

2022-06-16 16:42 UTC, arbrandes commented on .github/workflows/ci.yml
> +      uses: codecov/codecov-action@v3
Nitpick: can we get a newline at the end of the file?

2022-06-28 19:05 UTC, jmbowman commented
@arbrandes Looks like the requested change was made, do you want to update your review?  It's currently blocking merging.

2022-07-28 10:53 UTC, arbrandes approved these changes
Apologies for the delay.  Looks good to me!

2022-07-28 10:54 UTC, merged

2022-07-28 10:56 UTC, edx-semantic-release commented
:tada: This PR is included in version 12.0.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@edx/frontend-build/v/12.0.3)
- [GitHub release](https://github.com/openedx/frontend-build/releases/tag/v12.0.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: