feat: add option to public path cdn
openedx/frontend-build pull request #398
Opened 2023-06-21 21:10 UTC by johanv26

# Description
The idea of this commit is to add the option to manage the PublicPath of webpack to use CDN routing. 
Here you can see that this is managed by webpack, the problem is that `publicPatch` is also used in frontend platform with other purposes. So if I override publicPath the built id loading statics in the correct behaviour but frontend platform starts with problems.

## webpack recomendation

https://webpack.js.org/configuration/output/#outputpublicpath

## frontend platform
https://github.com/eduNEXT/frontend-platform/blob/5db061284ea0b6c02ed4601012ec1b150ac767d7/src/initialize.js#L92

So with this change I can affect only the webpack behaviour without affectin the history web browser of CDN.

### Before
![image](https://github.com/openedx/frontend-build/assets/51926076/8c8cfd21-e3f6-4427-9828-b6a350249b1a)

![Screenshot from 2023-06-20 14-52-18](https://github.com/openedx/frontend-build/assets/51926076/d9ae4668-3645-46f3-8d76-8946436d7851)

### After
![image](https://github.com/openedx/frontend-build/assets/51926076/56632110-f50c-4242-adb2-952a3d231fb6)

![image](https://github.com/openedx/frontend-build/assets/51926076/efea1dce-b74e-48c3-b235-623b56ebf497)

2023-06-21 21:10 UTC, openedx-webhooks commented
Thanks for the pull request, @johanv26!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-06-27 08:05 UTC, itsjeyd commented
Hi @johanv26, thank you for this contribution! Are the changes ready for review?

2023-06-27 14:02 UTC, johanv26 commented
> Hi @johanv26, thank you for this contribution! Are the changes ready for review?

Yes, they are. Thanks for your attention.

2023-06-28 12:11 UTC, itsjeyd commented
@johanv26 No problem! I'm marking this as ready for a test run.

2023-07-18 07:51 UTC, itsjeyd commented
Hey @arbrandes, based on Ed's request for review above I just wanted to check in and see if this PR is on your radar? It doesn't seem to have made it into your [queue](https://github.com/openedx/axim-engineering/issues/696) yet.

2023-07-19 15:10 UTC, arbrandes commented
Indeed, it wasn't on the review queue yet, in spite of having assigned myself.  Adding it now!

2023-07-26 08:33 UTC, itsjeyd commented
Great, thanks @arbrandes!

2023-09-13 12:54 UTC, itsjeyd commented
Hey @arbrandes, any updates on when you might get around to reviewing this PR?

CC @johanv26

2023-09-20 18:13 UTC, arbrandes requested changes
I don't doubt that the handling of `PUBLIC_PATH` in frontend-build and frontend-platform is too overloaded and thus prone to edge-case failures like the one described here, I'd first like to understand exactly that the failure being fixed is, so that we can:

1. Document how to work around it by using a separate variable like you suggest here;
2. Write unit tests that shield us from similar cases in the future.

With that in mind, do you mind giving us a step-by-step of how to reproduce the problem being fixed here?

2023-09-21 15:42 UTC, johanv26 commented
## Problem
This is something that appears when you want to host MFE in buckets or use CDN to speed its loading.
In summary, the problem is when you set a `publicPath` with and URL with protocol instead of only a path.
 eg `https://d20blt6w1kfasr.cloudfront.net/learning` instead `/learning/`
Technically webpack allows that in order to configure your generated assets targeting to another URL, like a CDN.

![image](https://github.com/openedx/frontend-build/assets/51926076/0dc4ceaf-7ca1-4d2f-9133-f7a79821e465)
So the produced HTML in dist would have assets targeting a CDN or a different URL.
![image](https://github.com/openedx/frontend-build/assets/51926076/9602efab-f7fa-4e8e-b08f-f1f01507875d)

## Reproduce
Ok, I am going to describe how to reproduce the problem.
So I didn't test it without a CDN but I thought you could test configuring in `PublicPath` a URL   instead of `/learning/`
something like `http://apps.{domain}:2000/learning/`.

So with that change, the learning MFE would stop working.

## Cause
Researching a little I found that problem is the history module because the PublicPath is used in this module as basename.
https://github.com/openedx/frontend-platform/blob/master/src/initialize.js#L102
Checking in history module in our version 
https://github.com/remix-run/history/blob/v4.5.1/modules/createBrowserHistory.js#L33
I found that the basename is used with a strip-prefix.
https://github.com/remix-run/history/blob/v4.5.1/modules/createBrowserHistory.js#L52-L64
So the basename defined with a complete URL doesn't work the same in the strip, because is expected to remove the `learning`.
I tried to reproduce the lines of code of the history module.
![2023-09-21_10-27](https://github.com/openedx/frontend-build/assets/51926076/6c721f86-7bb7-4d07-ac43-87811b8fd9d4)

## Current solution

My current solution is to configure 2 variables for the "PublicPath". one for webpack and the other one for history code would use.
```
PUBLIC_PATH_CDN: https://d20blt6w1kfasr.cloudfront.net/learning
PUBLIC_PATH: /learning/
```
With this solution webpack would use  `PUBLIC_PATH_CDN` so would create the assets targeting the CDN.
And the part of history would still be using the `PUBLIC_PATH` so the history module don't break.

2023-09-22 14:12 UTC, arbrandes commented
I see the problem.  But if we introduce a related by separately defined variable, then you force the operator to keep both of them synchronized, otherwise things will fail in different ways.

What would it take for us to support PUBLIC_PATH as Webpack originally intended it, instead?

2023-09-22 22:35 UTC, johanv26 commented
> I see the problem. But if we introduce a related but separately defined variable, then you force the operator to keep both of them synchronized, otherwise things will fail in different ways.
> 
> What would it take for us to support PUBLIC_PATH as Webpack originally intended it, instead?

I was thinking about whether and is possible to support PUBLIC_PATH as Webpack originally intended it ...

fix it in frontend-platform.
https://github.com/openedx/frontend-platform/blob/master/src/initialize.js#L102
So with this one if a `PUBLIC_PATH` is configured as a URL as webpack said, the frontend platform would take only the path.
https://github.com/eduNEXT/frontend-platform/compare/master...jlc/fix-capture-Public-Path
![image](https://github.com/openedx/frontend-build/assets/51926076/70e5486e-8118-46c8-8943-e6eceee713a4)
I would know your opinion if is a good way to get the path, but that is the idea.

2023-09-25 13:52 UTC, arbrandes commented
@johanv26, yes, that last suggestion seems like a good path forward!  Particularly if you can come up with some good unit tests to go with it! ;)

2023-09-26 02:22 UTC, johanv26 commented
Thanks @arbrandes, as you recommended I start the process with a PR in frontend-platform. I also add some unittests.
https://github.com/openedx/frontend-platform/pull/568/files :)

2023-09-26 02:23 UTC, johanv26 commented
Thanks @arbrandes, as you recommended I start the process with a PR in frontend-platform. I also add some unittests.
https://github.com/openedx/frontend-platform/pull/568/files :)

2023-09-26 02:23 UTC, johanv26 commented
Thanks @arbrandes, as you recommended I start the process with a PR in frontend-platform. I also add some unittests.
https://github.com/openedx/frontend-platform/pull/568/files :)

2023-09-26 07:07 UTC, itsjeyd commented
@johanv26 Does https://github.com/openedx/frontend-platform/pull/568 replace the changes from this PR, or complement them?

In other words, are the changes from this PR still needed or would it make sense to close this PR?

2023-09-26 16:04 UTC, johanv26 commented
@itsjeyd it makes sense to close this PR, but keep it msgs to conserve the context for the other PR.

2023-09-26 16:04 UTC, closed without merging

2023-09-26 16:04 UTC, openedx-webhooks commented
@johanv26 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-build&entry.867055334=https://github.com/openedx/frontend-build/pull/398&entry.1484655318=https://github.com/johanv26&entry.752974735=2023-06-21+21:10&entry.1917517419=2023-09-26+16:04&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->

2023-09-26 16:04 UTC, openedx-webhooks commented
@johanv26 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-build&entry.867055334=https://github.com/openedx/frontend-build/pull/398&entry.1484655318=https://github.com/johanv26&entry.752974735=2023-06-21+21:10&entry.1917517419=2023-09-26+16:04&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->